### ISSUE TITLE
[META] Upgrade to Django 2.2

### ISSUE THREAD

**Issue by theo-o** [tjcsl/ion#800]
[Django 2.2](https://docs.djangoproject.com/en/2.2/releases/2.2/) is the latest LTS release for Django and was released April 1, 2019.  Currently, Ion is running on Django 1.11 (which has reached the end of mainstream support with full EOL April 2020) (as per https://www.djangoproject.com/weblog/2015/jun/25/roadmap/). It should be a goal to upgrade to Django 2.2 sometime before 1.11's EOL.

This issue is meant to track blocker issues (please link to other issues below & feel free to edit):

- [ ] [django-formtools](https://github.com/django/django-formtools) currently has not had a release to add Django 2.2 compat (as per https://github.com/django/django-formtools/blob/master/docs/changelog.rst)

- [ ] [django-inline-svg](https://github.com/mixxorz/django-inline-svg) is marked only for compatibility with (and only [runs its build against](https://github.com/mixxorz/django-inline-svg/blob/master/tox.ini#L16)) Django 1.11-2.0 (and is also not actively maintained)

- [ ] [django-pipeline](https://github.com/jazzband/django-pipeline) runs its build against Django 1.6, 1.7, 1.8, 1.9, 1.10, 1.11, 2.0, and `master` (2.0 and `master` builds are marked as "allowed failures") [in CI using tox](https://github.com/jazzband/django-pipeline/blob/master/tox.ini#L16) (last commit January 26, build passed except for Django `master` build. The [last release](https://github.com/jazzband/django-pipeline/blob/38b4dad3c6418baf74c8267c733df07db6a3b508/.travis.yml) only runs tests up to Django 1.11.

- [x] [django-prometheus](https://github.com/korfuri/django-prometheus) has no marking of what versions are supported (though its build runs against Django 2.0 since [d0d171a](https://github.com/korfuri/django-prometheus/commit/d0d171ae5c2cddf230ea6f40599d9f47bb511754))

- [ ] [django-redis-sessions](https://github.com/martinrusev/django-redis-sessions) runs its build against the latest `django>1.5`, which passed against Python 3.6/Django 2.1 in the last commit in September 2018

- [ ] [django-request-logging-redux](https://github.com/tarkatronic/django-requestlogging) runs tests against all Django versions from 1.8 to 2.2, as well as the latest `master`, [in CI using tox](https://github.com/tarkatronic/django-requestlogging/blob/master/tox.ini#L19) (last commit June 26) (requires https://github.com/tjcsl/ion/issues/801)

- [x] [django-simple-history](https://github.com/treyhunner/django-simple-history/releases/tag/2.7.3) needs to be upgraded to 2.7.3 to gain official [2.2 support](https://github.com/treyhunner/django-simple-history/releases/tag/2.7.3)

- [x] [django-widget-tweaks](https://github.com/jazzband/django-widget-tweaks) runs tests against Django 1.8, 1.11, 2.0, 2.1, 2.2, and `master`, [in CI using tox](https://github.com/jazzband/django-widget-tweaks/blob/master/tox.ini#L11) (last commit June 8)

- [ ]

**Comment by theo-o** [comment]
As described in `django-channel`'s [changelog](https://github.com/django/channels/blob/56bb2b9afc9207d19a66d78f39a8e337cde93551/CHANGELOG.txt#L10), support for versions lower than Django 2.2 is being dropped upstream.
